### ISSUE TITLE
картка  флекси

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/User-card#2]
https://github.com/VasylUlianovskyi/User-card/blob/e38a8372bd3ca01b77fdcbb22995ca6b90cf9bde/assest/css/style.css#L26
 - картка складається всього з 2х блоків, які і так як блокові елементи будуть займати всю ширину картки, тому тут можна не ускладнювати собі життя і обійтись без флексів:
```css
.user-card {
  padding: 1rem;
  /* flex-grow: 1; */
  /* flex-shrink: 2; */
  max-width: 300px;
  min-width: 200px;
  width: 100%;
  /* flex-basis: 400px; */
  text-align: center;
}
``` 
Границя задається самим дочірнім елементам, тут її можна прибрати, вона не грає ролі.

`flex-basis` тут не відіграє ролі, оскільки він більший за максимально доступну ширину. Відповідно, через це ж `flex-grow` також не відпрацює, оскільки `flex-grow` - це дозвіл зростати більше за  `flex-basis`, а тут це не вийде. Можна задати `flex-basis` 250px, тоді буде ефект. 
- `flex-basis` - бажаний розмір, при досягненні якого буде перенос на новий рядок.
- `flex-grow` - дозвіл збільшуватись відносно цього бажаного розміру, якщо в рядку є для цього місце.
- `flex-shrink` - дозвіл зменшуватись, коли картка вже одна на рядку.
Алгоритм такий:
1. якщо по головній вісі не вистачає місця для елементів з шириною `flex-basis` і **елементів кілька**, то спрацьовує перенесення на новий рядок.
2. якщо по головній вісі не вистачає місця для елементів з шириною `flex-basis` і **елемент один**, то починається звуження елемента, якщо `flex-shrink` дозволяє.
